In [ ]:
# install the first package for computing log-signature: iisignature
!pip install iisignature

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
#install the second package for computing log-signature: esig
!pip install esig

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np
import iisignature as iisig
import esig 

**Now create a 2-dimensional random path with 20 data points**

In [ ]:
path_dim=2
path = np.random.uniform( size =(20 ,path_dim) )
print(path)

[[0.35769474 0.50588281]
 [0.66054619 0.43734089]
 [0.71378357 0.6613645 ]
 [0.82375704 0.42753399]
 [0.47864617 0.08956569]
 [0.65638669 0.71288493]
 [0.81275612 0.82707202]
 [0.79157413 0.83384043]
 [0.31244184 0.95926759]
 [0.37354168 0.29281042]
 [0.65100811 0.2666823 ]
 [0.39408311 0.05315378]
 [0.48518475 0.60916381]
 [0.77843437 0.09807013]
 [0.44793331 0.70795826]
 [0.91775239 0.24632245]
 [0.82708876 0.33930392]
 [0.3644781  0.67240777]
 [0.54137349 0.60588729]
 [0.59063857 0.78339926]]


**Choose the depth of (log)-signature we want to truncate**

In [ ]:
depth=3

**1. let us compare signatures generated from the two packages**

In [ ]:
signature_iisig = iisig.sig( path ,depth)
print(signature_iisig)

[ 0.23294383  0.27751645  0.02713141  0.10886414 -0.0442184   0.03850769
  0.0021067   0.0012721   0.02281503 -0.02105356 -0.01655772  0.07231872
 -0.04229502  0.00356217]


In [ ]:
signature_esig = esig.stream2sig(path, depth)
print(signature_esig[1:])

[ 0.23294383  0.27751645  0.02713141  0.10886414 -0.0442184   0.03850769
  0.0021067   0.0012721   0.02281503 -0.02105356 -0.01655772  0.07231872
 -0.04229502  0.00356217]


**2. compare the log-signatures generated from the two packages**

In [ ]:
s = iisig.prepare (path_dim ,depth)
logsignature_iisig = iisig.logsig (path ,s)
print(logsignature_iisig)

[ 0.23294383  0.27751645  0.07654127 -0.01015261 -0.03466434]


In [ ]:
logsignature_esig = esig.stream2logsig(path ,depth)
print(logsignature_esig)

[ 0.23294383  0.27751645  0.07654127 -0.01015261  0.03466434]


**3. examine the differences in the basis**

In [ ]:
iisig.basis(s)

('1', '2', '[1,2]', '[1,[1,2]]', '[[1,2],2]')

In [ ]:
log_esig_keys = esig.logsigkeys(path_dim, depth)
print(log_esig_keys) 

 1 2 [1,2] [1,[1,2]] [2,[1,2]]
